"""empty message

Revision ID: a83a725c7ac5
Revises: 
Create Date: 2020-06-05 13:25:19.907640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a83a725c7ac5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserData', sa.Column('googleAssoc', sa.Boolean(), nullable=True))
    op.add_column('UserData', sa.Column('googleID', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'UserData', ['googleID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UserData', type_='unique')
    op.drop_column('UserData', 'googleID')
    op.drop_column('UserData', 'googleAssoc')
    # ### end Alembic commands ###
