"""empty message

Revision ID: bd2054290318
Revises: a83a725c7ac5
Create Date: 2020-06-07 15:57:11.561428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd2054290318'
down_revision = 'a83a725c7ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserData', 'googleID')
    op.drop_column('UserData', 'googleAssoc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserData', sa.Column('googleAssoc', sa.BOOLEAN(), nullable=True))
    op.add_column('UserData', sa.Column('googleID', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
